import { Convergence } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import BackgroundProvider from "@/components/BackgroundProvider";

const convergence = Convergence({
  variable: "--font-convergence",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Project Ignite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${convergence.variable} font-sans antialiased`}>
          <BackgroundProvider>
            <Navbar />
            <main
              className="min-h-screen flex justify-center"
              style={{
                background: `linear-gradient(to bottom, var(--bg-top), var(--bg-middle), var(--bg-bottom))`,
              }}
            >
              {children}
            </main>
          </BackgroundProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
