export const alignmentOptions = [
  { label: "Good :", value: "", disabled: true },
  { label: "Lawful Good", value: "Lawful Good" },
  { label: "Neutral Good", value: "Neutral Good" },
  { label: "Chaotic Good", value: "Chaotic Good" },

  { label: "Neutral :", value: "", disabled: true },
  { label: "Lawful Neutral", value: "Lawful Neutral" },
  { label: "True Neutral", value: "True Neutral" },
  { label: "Chaotic Neutral", value: "Chaotic Neutral" },

  { label: "Evil :", value: "", disabled: true },
  { label: "Lawful Evil", value: "Lawful Evil" },
  { label: "Neutral Evil", value: "Neutral Evil" },
  { label: "Chaotic Evil", value: "Chaotic Evil" },

  { label: "Other :", value: "", disabled: true },
  { label: "Unknown", value: "Unknown" },
  { label: "Unaligned", value: "Unaligned" },
];

export const allTraitsOptions = [
  "Innocent",
  "Sage",
  "Explorer",
  "Outlaw",
  "Magician",
  "Hero",
  "Lover",
  "Jester",
  "Everyman",
  "Caregiver",
  "Ruler",
  "Creator",
];

export const economicalOptions = [
  "Poor/Subsistence",
  "Modest/Working Class",
  "Middle-Class/Comfortable",
  "Wealthy/Affluent",
  "Rich/Prosperous",
  "Opulent/Lavish",
];

export const socialClassOptions = [
  "Slave/Serf",
  "Criminal/Outlaw",
  "Exile/Outcast",
  "Marginalized",
  "Commoners/Workers",
  "Merchants/Artisans",
  "Military/Officials",
  "Clergy/Priest",
  "Scholars/Intelligentsia",
  "Politician",
  "Knight / Dame",
  "Nobility/Large Land Owner",
  "High Nobility/Elite",
  "Rulers/Sovereigns",
];

export const familyOptions = [
  { label: "Main Family :", value: "", disabled: true },
  { label: "Father", value: "Father" },
  { label: "Mother", value: "Mother" },
  { label: "Husband", value: "Husband" },
  { label: "Wife", value: "Wife" },
  { label: "Son", value: "Son" },
  { label: "Daughter", value: "Daughter" },
  { label: "Brother", value: "Brother" },
  { label: "Sister", value: "Sister" },
  { label: "Older Sister", value: "Older Sister" },
  { label: "Little Sister", value: "Little Sister" },
  { label: "Twin Sister", value: "Twin Sister" },
  { label: "Adopted Sister", value: "Adopted Sister" },
  { label: "Older Brother", value: "Older Brother" },
  { label: "Little Brother", value: "Little Brother" },
  { label: "Twin Brother", value: "Twin Brother" },
  { label: "Adopted Brother", value: "Adopted Brother" },

  { label: "Brother", value: "Brother" },
  { label: "Sister", value: "Sister" },
  { label: "Older Sister", value: "Older Sister" },
  { label: "Wife", value: "Wife" },
  { label: "Son", value: "Son" },
  { label: "Daughter", value: "Daughter" },

  { label: "Larger Family :", value: "", disabled: true },
  { label: "Grandfather", value: "Grandfather" },
  { label: "Grandmother", value: "Grandmother" },
  { label: "Uncle", value: "Uncle" },
  { label: "Aunt", value: "Aunt" },
  { label: "Cousin", value: "Cousin" },
  { label: "Nephew", value: "Nephew" },
  { label: "Niece", value: "Niece" },
  { label: "Son in Law", value: "Son in Law" },
  { label: "Daughter in Law", value: "Daughter in Law" },

  { label: "Blended Family :", value: "", disabled: true },
  { label: "Half Brother", value: "Half Brother" },
  { label: "Half Sister", value: "Half Sister" },
  { label: "Step Mother", value: "Step Mother" },
  { label: "Step Father", value: "Step Father" },

  { label: "Partner Family :", value: "", disabled: true },
  { label: "Father In Law", value: "Father In Law" },
  { label: "Mother In Law", value: "Mother In Law" },
  { label: "Sister In Law", value: "Sister In Law" },
  { label: "Brother In Law", value: "Brother In Law" },
  { label: "Niece In Law", value: "Niece In Law" },
  { label: "Nephew In Law", value: "Nephew In Law" },
  { label: "Uncle In Law", value: "Uncle In Law" },
  { label: "Aunt In Law", value: "Aunt In Law" },
  { label: "Cousin In Law", value: "Cousin In Law" },
  { label: "Grandfather In Law", value: "Grandfather In Law" },
  { label: "Grandmother In Law", value: "Grandmother In Law" },
];

export const alliesOptions = [
  { label: "Social Allies :", value: "", disabled: true },
  { label: "Companion", value: "Companion" },
  { label: "Acquaintance", value: "Acquaintance" },
  { label: "Mentor", value: "Mentor" },
  { label: "Student", value: "Student" },
  { label: "Rival (turned ally)", value: "Rival (turned ally)" },
  { label: "Neighbour", value: "Neighbour" },

  { label: "Professional Allies :", value: "", disabled: true },
  { label: "Colleague", value: "Colleague" },
  { label: "Business Partner", value: "Business Partner" },
  { label: "Employer", value: "Employer" },
  { label: "Employee", value: "Employee" },
  { label: "Client", value: "Client" },
  { label: "Patron", value: "Patron" },
  { label: "Benefactor", value: "Benefactor" },
  { label: "Sponsor", value: "Sponsor" },
  { label: "Apprentice", value: "Apprentice" },
  { label: "Master", value: "Master" },
  { label: "Guild Member", value: "Guild Member" },
  { label: "Guild Leader", value: "Guild Leader" },

  { label: "Military & Adventuring Allies :", value: "", disabled: true },
  { label: "Comrade-in-arms", value: "Comrade-in-arms" },
  { label: "Commander", value: "Commander" },
  { label: "Soldier Ally", value: "Soldier Ally" },
  { label: "Mercenary Partner", value: "Mercenary Partner" },
  { label: "Squad mate", value: "Squad mate" },
  { label: "Battle Brother / Sister", value: "Battle Brother / Sister" },
  { label: "Adventuring Party Member", value: "Adventuring Party Member" },
  { label: "Squire", value: "Squire" },
  { label: "Scout", value: "Scout" },

  { label: "Political & Ideological Allies :", value: "", disabled: true },
  { label: "Faction Member", value: "Faction Member" },
  { label: "Rebel Ally", value: "Rebel Ally" },
  { label: "Diplomatic Contact", value: "Diplomatic Contact" },
  { label: "Spy Contact", value: "Spy Contact" },
  { label: "Political Patron", value: "Political Patron" },
  { label: "Noble Supporter", value: "Noble Supporter" },
  { label: "Revolutionary Ally", value: "Revolutionary Ally" },
  { label: "Cultist Ally", value: "Cultist Ally" },
  { label: "Religious Devotee", value: "Religious Devotee" },
  { label: "Fellow Believer", value: "Fellow Believer" },

  { label: "Supernatural & Otherworldly Allies :", value: "", disabled: true },
  { label: "Familiar", value: "Familiar" },
  { label: "Summoned Creature", value: "Summoned Creature" },
  { label: "Bound Spirit", value: "Bound Spirit" },
  { label: "Guardian Angel", value: "Guardian Angel" },
  { label: "Elemental Ally", value: "Elemental Ally" },
  { label: "Patron", value: "Patron" },
  { label: "Sentient Weapon / Relic", value: "Sentient Weapon / Relic" },
  { label: "Magical Construct", value: "Magical Construct" },
  { label: "Beast Companion", value: "Beast Companion" },

  { label: "Community Allies :", value: "", disabled: true },
  { label: "Local Elder", value: "Local Elder" },
  { label: "Village Leader", value: "Village Leader" },
  { label: "Healer / Doctor", value: "Healer / Doctor" },
  { label: "Teacher", value: "Teacher" },
  { label: "Scholar Ally", value: "Scholar Ally" },
  { label: "Craftsman Ally", value: "Craftsman Ally" },
  { label: "Merchant Ally", value: "Merchant Ally" },
];

export const friendsOptions = [
  { label: "By Bond :", value: "", disabled: true },
  { label: "Best Friend", value: "Best Friend" },
  { label: "Close Friend", value: "Close Friend" },
  { label: "Casual Friend", value: "Casual Friend" },
  { label: "Childhood Friend", value: "Childhood Friend" },
  { label: "Family Friend", value: "Family Friend" },

  { label: "By Role :", value: "", disabled: true },
  { label: "Confidant", value: "Confidant" },
  { label: "Partner-in-Crime", value: "Partner-in-Crime" },
  {
    label: "Drinking Buddy / Leisure Friend",
    value: "Drinking Buddy / Leisure Friend",
  },
  { label: "Work Friend", value: "Work Friend" },
  { label: "Travel Companion", value: "Travel Companion" },
  { label: "Study Friend / Classmate", value: "Study Friend / Classmate" },
  { label: "Sparring Partner", value: "Sparring Partner" },

  { label: "By Nature of Relationship :", value: "", disabled: true },
  { label: "Loyal Friend", value: "Loyal Friend" },
  { label: "Fair-Weather Friend", value: "Fair-Weather Friend" },
  { label: "Long-Distance Friend", value: "Long-Distance Friend" },
  { label: "Rival-Friend", value: "Rival-Friend" },
  { label: "Secret Friend", value: "Secret Friend" },

  { label: "By Depth of Impact :", value: "", disabled: true },
  { label: "Mentor-Friend", value: "Mentor-Friend" },
  { label: "Idolized Friend", value: "Idolized Friend" },
  { label: "Protective Friend", value: "Protective Friend" },
  { label: "Dependent Friend", value: "Dependent Friend" },
  { label: "Unexpected Friend", value: "Unexpected Friend" },
];

export const enemiesOptions = [
  { label: "By Relationship :", value: "", disabled: true },
  { label: "Parent Opponent", value: "Parent Opponent" },
  { label: "Sin of the Father", value: "Sin of the Father" },
  { label: "Kin Opponent", value: "Kin Opponent" },
  { label: "Relative Enemy", value: "Relative Enemy" },
  { label: "Former Ally", value: "Former Ally" },
  { label: "Former Business Partner", value: "Former Business Partner" },
  { label: "Former Adventurer Partner", value: "Former Adventurer Partner" },
  { label: "Former Crime Partner", value: "Former Crime Partner" },
  { label: "Jealous Peer", value: "Jealous Peer" },
  { label: "Jealous Enemy", value: "Jealous Enemy" },
  { label: "Spurned Lover / Ex-Lover", value: "Spurned Lover / Ex-Lover" },
  { label: "Ex-Friend turned Betrayer", value: "Ex-Friend turned Betrayer" },
  { label: "Teacher turned Enemy", value: "Teacher turned Enemy" },
  { label: "Student turned Enemy", value: "Student turned Enemy" },
  { label: "Mentor turned Betrayer", value: "Mentor turned Betrayer" },

  { label: "Friendship & Social Betrayal :", value: "", disabled: true },
  {
    label: "Childhood Friend turned Rival",
    value: "Childhood Friend turned Rival",
  },
  { label: "Best Friend turned Enemy", value: "Best Friend turned Enemy" },
  {
    label: "Trusted Confidant turned Betrayer",
    value: "Trusted Confidant turned Betrayer",
  },
  { label: "Ally who Turned Jealous", value: "Ally who Turned Jealous" },
  { label: "Roommate turned Enemy", value: "Roommate turned Enemy" },
  { label: "Guildmate turned Enemy", value: "Guildmate turned Enemy" },
  {
    label: "Party Member turned Betrayer",
    value: "Party Member turned Betrayer",
  },

  { label: "By Role :", value: "", disabled: true },
  { label: "Political Enemy", value: "Political Enemy" },
  { label: "Business/Trade Competitor", value: "Business/Trade Competitor" },
  { label: "Military Enemy", value: "Military Enemy" },
  { label: "Religious Enemy", value: "Religious Enemy" },
  { label: "Criminal Enemy", value: "Criminal Enemy" },
  { label: "Academic Rival", value: "Academic Rival" },
  { label: "Professional Rival", value: "Professional Rival" },
  { label: "Workplace Rival", value: "Workplace Rival" },
  { label: "Supervisor turned Enemy", value: "Supervisor turned Enemy" },
  { label: "Subordinate turned Enemy", value: "Subordinate turned Enemy" },

  { label: "By Conflict :", value: "", disabled: true },
  { label: "Rival", value: "Rival" },
  { label: "Nemesis", value: "Nemesis" },
  { label: "Arch-Enemy", value: "Arch-Enemy" },
  { label: "Opponent", value: "Opponent" },
  { label: "Challenger", value: "Challenger" },
  { label: "Antagonist", value: "Antagonist" },

  { label: "Nature of Conflict :", value: "", disabled: true },
  { label: "Personal Enemy", value: "Personal Enemy" },
  { label: "Ideological Enemy", value: "Ideological Enemy" },
  { label: "Situational Enemy", value: "Situational Enemy" },
  { label: "Secret Enemy", value: "Secret Enemy" },
  { label: "Passive Enemy", value: "Passive Enemy" },
  { label: "Active Enemy", value: "Active Enemy" },
  { label: "Temporary Enemy", value: "Temporary Enemy" },

  { label: "Community & Other Enemies :", value: "", disabled: true },
  { label: "Neighbor Rival", value: "Neighbor Rival" },
  { label: "Community Outcast", value: "Community Outcast" },
  { label: "Clan Enemy", value: "Clan Enemy" },
  { label: "Faction Betrayer", value: "Faction Betrayer" },
  { label: "Cultural Enemy", value: "Cultural Enemy" },
];

export const subordinatesOptions = [
  { label: "Military Subordinates :", value: "", disabled: true },
  { label: "Soldier", value: "Soldier" },
  { label: "Sergeant", value: "Sergeant" },
  { label: "Lieutenant", value: "Lieutenant" },
  { label: "Captain", value: "Captain" },

  { label: "Professional Subordinates :", value: "", disabled: true },
  { label: "Assistant", value: "Assistant" },
  { label: "Secretary", value: "Secretary" },
  { label: "Intern", value: "Intern" },
  { label: "Apprentice", value: "Apprentice" },

  { label: "Other Subordinates :", value: "", disabled: true },
  { label: "Minion", value: "Minion" },
  { label: "Servant", value: "Servant" },
  { label: "Slave", value: "Slave" },
  { label: "Follower", value: "Follower" },
];

export const affiliationsOptions = [
  { label: "Membership / Rank", value: "", disabled: true },
  { label: "Founder", value: "Founder" },
  { label: "Leader", value: "Leader" },
  { label: "Commander", value: "Commander" },
  { label: "Captain", value: "Captain" },
  { label: "Officer", value: "Officer" },
  { label: "Council Member", value: "Council Member" },
  { label: "Veteran", value: "Veteran" },
  { label: "Senior Member", value: "Senior Member" },
  { label: "Member", value: "Member" },
  { label: "Agent", value: "Agent" },
  { label: "Recruit", value: "Recruit" },
  { label: "Initiate", value: "Initiate" },
  { label: "Trainee", value: "Trainee" },

  { label: "External Roles", value: "", disabled: true },
  { label: "Ally", value: "Ally" },
  { label: "Partner / Associate", value: "Partner / Associate" },
  { label: "Patron / Sponsor", value: "Patron / Sponsor" },
  { label: "Benefactor", value: "Benefactor" },
  { label: "Contractor / Mercenary", value: "Contractor / Mercenary" },
  { label: "Supplier / Trader", value: "Supplier / Trader" },

  { label: "Hostile / Adversarial", value: "", disabled: true },
  { label: "Rival", value: "Rival" },
  { label: "Competitor", value: "Competitor" },
  { label: "Opponent", value: "Opponent" },
  { label: "Saboteur", value: "Saboteur" },
  { label: "Enemy Combatant", value: "Enemy Combatant" },
  { label: "Rebel / Insurgent", value: "Rebel / Insurgent" },
  { label: "Dissenter / Dissident", value: "Dissenter / Dissident" },
  { label: "Defector", value: "Defector" },
  { label: "Betrayer", value: "Betrayer" },
  { label: "Conspirator", value: "Conspirator" },
  { label: "Rival Claimant", value: "Rival Claimant" },
  { label: "Vendetta Holder", value: "Vendetta Holder" },
  { label: "Usurper", value: "Usurper" },
  { label: "Traitor Hunter", value: "Traitor Hunter" },
  { label: "Blacklisted / Wanted", value: "Blacklisted / Wanted" },
  { label: "Exterminator / Purger", value: "Exterminator / Purger" },
  { label: "Enemy Through Contract", value: "Enemy Through Contract" },
  { label: "Enemy Through Mutuality", value: "Enemy Through Mutuality" },

  { label: "Loyalty / Standing", value: "", disabled: true },
  { label: "Loyalist / Devoted", value: "Loyalist / Devoted" },
  { label: "Respected / Honored Member", value: "Respected / Honored Member" },
  { label: "Neutral / Passive Member", value: "Neutral / Passive Member" },
  { label: "Suspicious / Distrusted", value: "Suspicious / Distrusted" },
  { label: "Rival Member", value: "Rival Member" },
  { label: "Exiled / Outcast", value: "Exiled / Outcast" },
  { label: "Betrayer / Traitor", value: "Betrayer / Traitor" },
  { label: "Former Member", value: "Former Member" },

  { label: "Special Bonds", value: "", disabled: true },
  { label: "Heir / Successor", value: "Heir / Successor" },
  { label: "Champion / Representative", value: "Champion / Representative" },
  { label: "Envoy / Messenger", value: "Envoy / Messenger" },
  { label: "Spy / Informant", value: "Spy / Informant" },
  { label: "Protector / Guardian", value: "Protector / Guardian" },
  { label: "Symbol / Figurehead", value: "Symbol / Figurehead" },
];

export const attributesOptions = [
  { key: "str", label: "Strength", skills: ["Athletics"] },
  {
    key: "dex",
    label: "Dexterity",
    skills: ["Acrobatics", "Sleight of Hand", "Stealth"],
  },
  { key: "con", label: "Constitution", skills: [] },
  {
    key: "int",
    label: "Intelligence",
    skills: ["Arcana", "History", "Investigation", "Nature", "Religion"],
  },
  {
    key: "wis",
    label: "Wisdom",
    skills: [
      "Animal Handling",
      "Insight",
      "Medicine",
      "Perception",
      "Survival",
    ],
  },
  {
    key: "cha",
    label: "Charisma",
    skills: ["Deception", "Intimidation", "Performance", "Persuasion"],
  },
];

export const combatValueOptions = [
  { value: 0, label: "Commoner", baseValues: [10, 10, 10, 10, 10, 10] },
  { value: 1, label: "Novice", baseValues: [8, 10, 10, 10, 12, 12] },
  { value: 2, label: "Adept", baseValues: [8, 10, 10, 10, 12, 13] },
  { value: 3, label: "Journeyman", baseValues: [8, 10, 10, 12, 12, 13] },
  { value: 4, label: "Veteran", baseValues: [8, 10, 10, 12, 13, 13] },
  { value: 5, label: "Champion", baseValues: [8, 10, 10, 12, 13, 14] },
  { value: 6, label: "Hero", baseValues: [8, 10, 12, 12, 13, 14] },
  { value: 7, label: "Guardian", baseValues: [8, 10, 12, 13, 13, 14] },
  { value: 8, label: "Warden", baseValues: [8, 10, 12, 13, 14, 14] },
  { value: 9, label: "Paragon", baseValues: [8, 10, 12, 14, 14, 14] },
  { value: 10, label: "Legend", baseValues: [8, 10, 12, 14, 14, 15] },
  { value: 11, label: "Exemplar", baseValues: [8, 10, 12, 14, 15, 15] },
  { value: 12, label: "Vanguard", baseValues: [8, 10, 12, 15, 15, 15] },
  { value: 13, label: "Conqueror", baseValues: [8, 10, 12, 15, 15, 16] },
  { value: 14, label: "Archon", baseValues: [8, 10, 12, 15, 16, 16] },
  { value: 15, label: "Mythic", baseValues: [8, 10, 12, 16, 16, 16] },
  { value: 16, label: "Luminary", baseValues: [8, 10, 13, 16, 16, 16] },
  { value: 17, label: "Chosen", baseValues: [8, 10, 13, 16, 16, 17] },
  { value: 18, label: "Sovereign", baseValues: [8, 10, 13, 16, 17, 17] },
  { value: 19, label: "Icon", baseValues: [8, 10, 14, 16, 17, 17] },
  { value: 20, label: "World-Hero", baseValues: [10, 12, 16, 18, 19, 20] },
  { value: 21, label: "Ascendant", baseValues: [10, 12, 16, 18, 19, 21] },
  { value: 22, label: "Oracle", baseValues: [10, 12, 16, 19, 19, 21] },
  { value: 23, label: "Transcendent", baseValues: [10, 12, 16, 19, 20, 21] },
  { value: 24, label: "Eternal", baseValues: [10, 12, 17, 19, 20, 21] },
  { value: 25, label: "Worldbreaker", baseValues: [10, 12, 17, 19, 20, 22] },
  { value: 26, label: "High Exemplar", baseValues: [10, 12, 17, 20, 20, 22] },
  { value: 27, label: "Titanborn", baseValues: [10, 12, 17, 20, 21, 22] },
  { value: 28, label: "Arch-Eternal", baseValues: [10, 12, 18, 20, 21, 22] },
  { value: 29, label: "Herald", baseValues: [10, 12, 18, 20, 21, 23] },
  { value: 30, label: "Demi-Legend", baseValues: [10, 12, 18, 21, 21, 23] },
  { value: 31, label: "Immortal", baseValues: [10, 12, 18, 21, 22, 23] },
  { value: 32, label: "Radiant One", baseValues: [10, 12, 19, 21, 22, 23] },
  { value: 33, label: "Celestial", baseValues: [10, 12, 19, 21, 22, 24] },
  { value: 34, label: "Avatar", baseValues: [10, 12, 19, 22, 22, 24] },
  { value: 35, label: "Demi-Deity", baseValues: [10, 12, 19, 22, 23, 24] },
  { value: 36, label: "Eternal Flame", baseValues: [10, 12, 20, 22, 23, 24] },
  { value: 37, label: "World-Bearer", baseValues: [10, 12, 20, 22, 23, 25] },
  { value: 38, label: "God-Touched", baseValues: [10, 12, 20, 23, 23, 25] },
  {
    value: 39,
    label: "Divine Incarnate",
    baseValues: [10, 12, 20, 23, 24, 26],
  },
  { value: 40, label: "Demi-God", baseValues: [10, 12, 20, 24, 26, 30] },
];

export const sizeOptions = [
  { label: "Tiny", value: "tiny", vtt: "tiny" },
  { label: "Small", value: "small", vtt: "sm" },
  { label: "Medium", value: "medium", vtt: "med" },
  { label: "Large", value: "large", vtt: "lg" },
  { label: "Huge", value: "huge", vtt: "huge" },
  { label: "Gargantuan", value: "gargantuan", vtt: "gtg" },
];

export const creatureTypeOptions = [
  "Humanoid",
  "Aberration",
  "Beast",
  "Celestial",
  "Construct",
  "Dragon",
  "Elemental",
  "Fey",
  "Fiend",
  "Giant",
  "Monstrosity",
  "Ooze",
  "Plant",
  "Undead",
];

export const personalityCombatStyleOptions = [
  { label: "-Aggressive Types-", value: "", disabled: true },
  {
    label: "Brutal → Overwhelms foes with raw power, no finesse.",
    value: "Brutal → Overwhelms foes with raw power, no finesse.",
  },
  {
    label: "Savage → Animalistic, tears into enemies without restraint.",
    value: "Savage → Animalistic, tears into enemies without restraint.",
  },
  {
    label: "Berserker → Grows stronger the longer they fight, reckless.",
    value: "Berserker → Grows stronger the longer they fight, reckless.",
  },
  {
    label: "Relentless → Pursues one target until it falls, ignoring others.",
    value: "Relentless → Pursues one target until it falls, ignoring others.",
  },
  {
    label: "Opportunist → Attacks when the enemy is weakest or distracted.",
    value: "Opportunist → Attacks when the enemy is weakest or distracted.",
  },

  { label: "-Defensive / Controlled Types-", value: "", disabled: true },
  {
    label: "Protective → Prioritizes defending allies over striking back.",
    value: "Protective → Prioritizes defending allies over striking back.",
  },
  {
    label: "Guardian → Stands ground and absorbs punishment.",
    value: "Guardian → Stands ground and absorbs punishment.",
  },
  {
    label: "Calculated → Waits for openings, punishes mistakes.",
    value: "Calculated → Waits for openings, punishes mistakes.",
  },
  {
    label: "Patient → Prefers counterattacks and conserving energy.",
    value: "Patient → Prefers counterattacks and conserving energy.",
  },
  {
    label: "Warden → Controls space, denying enemy movement.",
    value: "Warden → Controls space, denying enemy movement.",
  },

  { label: "-Chaotic / Unstable Types-", value: "", disabled: true },
  {
    label: "Chaotic → Random attack patterns, unpredictable.",
    value: "Chaotic → Random attack patterns, unpredictable.",
  },
  {
    label: "Unstable → Fluctuates between passive and violent outbursts.",
    value: "Unstable → Fluctuates between passive and violent outbursts.",
  },
  {
    label: "Sadistic → Draws out fights, enjoys tormenting foes.",
    value: "Sadistic → Draws out fights, enjoys tormenting foes.",
  },
  {
    label: "Deceptive → Feigns weakness or tricks enemies before striking.",
    value: "Deceptive → Feigns weakness or tricks enemies before striking.",
  },
  {
    label: "Erratic → Moves and fights in ways that defy logic.",
    value: "Erratic → Moves and fights in ways that defy logic.",
  },

  { label: "-Tactical / Strategic Types-", value: "", disabled: true },
  {
    label: "Tactician → Plans several moves ahead, uses allies efficiently.",
    value: "Tactician → Plans several moves ahead, uses allies efficiently.",
  },
  {
    label: "Commander → Directs the battlefield, buffs allies, controls flow.",
    value: "Commander → Directs the battlefield, buffs allies, controls flow.",
  },
  {
    label: "Hunter → Tracks and isolates prey before striking.",
    value: "Hunter → Tracks and isolates prey before striking.",
  },
  {
    label: "Duelist → Seeks one-on-one combat, ignores others.",
    value: "Duelist → Seeks one-on-one combat, ignores others.",
  },
  {
    label: "Disruptor → Targets spellcasters, healers, or support first.",
    value: "Disruptor → Targets spellcasters, healers, or support first.",
  },

  { label: "-Supernatural / Thematic Types-", value: "", disabled: true },
  {
    label: "Fearmonger → Uses intimidation and aura effects to weaken morale.",
    value: "Fearmonger → Uses intimidation and aura effects to weaken morale.",
  },
  {
    label: "Hexer → Weakens enemies with curses before closing in.",
    value: "Hexer → Weakens enemies with curses before closing in.",
  },
  {
    label: "Fanatical → Fights with religious or ideological fervor.",
    value: "Fanatical → Fights with religious or ideological fervor.",
  },
  {
    label: "Bloodthirsty → Grows stronger the more blood is spilled.",
    value: "Bloodthirsty → Grows stronger the more blood is spilled.",
  },
  {
    label: "Stoic → Silent, unshaken, fights with eerie calm.",
    value: "Stoic → Silent, unshaken, fights with eerie calm.",
  },

  { label: "-Trickster Types-", value: "", disabled: true },
  {
    label: "Ambusher → Prefers surprise strikes and ambushes.",
    value: "Ambusher → Prefers surprise strikes and ambushes.",
  },
  {
    label: "Shadowstalker → Strikes from stealth, melts back into cover.",
    value: "Shadowstalker → Strikes from stealth, melts back into cover.",
  },
  {
    label: "Illusionist → Confuses enemies with tricks and misdirection.",
    value: "Illusionist → Confuses enemies with tricks and misdirection.",
  },
  {
    label: "Hit-and-Run → Strikes quickly, then retreats to regroup.",
    value: "Hit-and-Run → Strikes quickly, then retreats to regroup.",
  },
  {
    label: "Manipulator → Uses enemies against each other.",
    value: "Manipulator → Uses enemies against each other.",
  },
];

export const nationalityOptions = [
  { label: "Vallarian Nationality :", value: "", disabled: true },
  { label: "Mondralian", value: "Mondralian" },
  { label: "Delstainvian", value: "Delstainvian" },
  { label: "Istegrian", value: "Istegrian" },
  { label: "Alvavian", value: "Alvavian" },
  { label: "Kastugarian", value: "Kastugarian" },
  { label: "Kolgardian", value: "Kolgardian" },
  { label: "Magusvian", value: "Magusvian" },
  { label: "Prosperian", value: "Prosperian" },
  { label: "Tansarha", value: "Tansarha" },
  { label: "Other Nationality :", value: "", disabled: true },
  { label: "Non-National", value: "Non-National" },
  { label: "Titanfall People", value: "Titanfall People" },
  { label: "The Lost Isles People", value: "The Lost Isles People" },
  { label: "Other Planes", value: "Other Planes" },
  { label: "Astral Planes", value: "Astral Planes" },
  { label: "Unknown", value: "Unknown" },
];

export const countryOptions = [
  { label: "Vallarian Nationality :", value: "", disabled: true },
  { label: "Mondralia", value: "Mondralia" },
  { label: "Delstainvia", value: "Delstainvia" },
  { label: "Istegria", value: "Istegria" },
  { label: "Alvavia", value: "Alvavia" },
  { label: "Kastugaria", value: "Kastugaria" },
  { label: "Kolgardia", value: "Kolgardia" },
  { label: "Magusvia", value: "Magusvia" },
  { label: "Prospero", value: "Prospero" },
  { label: "Tansarha", value: "Tansarha" },
  { label: "Titanfall Isles :", value: "", disabled: true },
  { label: "The Titanfall Isle", value: "The Titanfall Isle" },
  { label: "The Isle of Dragons", value: "The Isle of Dragons" },
  { label: "Light & Shadow Isle", value: "Light & Shadow Isle" },
  { label: "Isle of Thorns", value: "Isle of Thorns" },
  { label: "Isle of Acheron", value: "Isle of Acheron" },
  { label: "Isle of Wild-Beast", value: "Isle of Wild-Beast" },
  { label: "Isle of Snow-Warmth", value: "Isle of Snow-Warmth" },
  { label: "Isle of Cinder", value: "Isle of Cinder" },
  { label: "Mythos Isle", value: "Mythos Isle" },
  { label: "Septuagint Isle", value: "Isle of Ouranós" },
  { label: "Isle of Septuagint", value: "Septuagint Isle" },
  { label: "Isle of Wyvern", value: "Isle of Wyvern" },
  { label: "Fomorians Fang", value: "Fomorians Fang" },
  { label: "Multiversal :", value: "", disabled: true },
  { label: "Material Plane (Terra)", value: "Material Plane (Terra)" },
  { label: "Elemental Plane of Water", value: "Elemental Plane of Water" },
  { label: "Elemental Plane of Air", value: "Elemental Plane of Air" },
  { label: "Elemental Plane of Fire", value: "Elemental Plane of Fire" },
  { label: "Elemental Plane of Earth", value: "Elemental Plane of Earth" },
  { label: "Feywild", value: "Feywild" },
  { label: "Shadowfell", value: "Shadowfell" },
  { label: "Celestia (Elysium)", value: "Celestia (Elysium)" },
  { label: "The Nine Hells", value: "The Nine Hells" },
  { label: "Other Nationality :", value: "", disabled: true },
  { label: "Non-National", value: "Non-National" },
  { label: "Demi-plane", value: "Demi-plane" },
  { label: "Other Planes", value: "Other Planes" },
  { label: "Astral Planes", value: "Astral Planes" },
  { label: "Unknown", value: "Unknown" },
];

export const damageTypesWithImages = [
  { value: "acid", label: "Acid", image: "/assets/damageType_icon/acid.webp" },
  { value: "cold", label: "Cold", image: "/assets/damageType_icon/cold.webp" },
  { value: "fire", label: "Fire", image: "/assets/damageType_icon/fire.webp" },
  {
    value: "force",
    label: "Force",
    image: "/assets/damageType_icon/force.webp",
  },
  {
    value: "lightning",
    label: "Lightning",
    image: "/assets/damageType_icon/lightning.webp",
  },
  {
    value: "necrotic",
    label: "Necrotic",
    image: "/assets/damageType_icon/necrotic.webp",
  },
  {
    value: "physic",
    label: "Physic",
    image: "/assets/damageType_icon/physic.webp",
  },
  {
    value: "physical",
    label: "Physical",
    image: "/assets/damageType_icon/physical.webp",
  },
  {
    value: "poison",
    label: "Poison",
    image: "/assets/damageType_icon/poison.webp",
  },
  {
    value: "radiant",
    label: "Radiant",
    image: "/assets/damageType_icon/radiant.webp",
  },
  {
    value: "thunder",
    label: "Thunder",
    image: "/assets/damageType_icon/thunder.webp",
  },
];
