export const familyOptions = [
  { label: "Main Family :", value: "", disabled: true },
  { label: "Father", value: "Father" },
  { label: "Mother", value: "Mother" },
  { label: "Husband", value: "Husband" },
  { label: "Wife", value: "Wife" },
  { label: "Son", value: "Son" },
  { label: "Daughter", value: "Daughter" },

  { label: "Larger Family :", value: "", disabled: true },
  { label: "Grandfather", value: "Grandfather" },
  { label: "Grandmother", value: "Grandmother" },
  { label: "Uncle", value: "Uncle" },
  { label: "Aunt", value: "Aunt" },
  { label: "Cousin", value: "Cousin" },
  { label: "Nephew", value: "Nephew" },
  { label: "Niece", value: "Niece" },
  { label: "Son in Law", value: "Son in Law" },
  { label: "Daughter in Law", value: "Daughter in Law" },

  { label: "Blended Family :", value: "", disabled: true },
  { label: "Half Brother", value: "Half Brother" },
  { label: "Half Sister", value: "Half Sister" },
  { label: "Step Mother", value: "Step Mother" },
  { label: "Step Father", value: "Step Father" },

  { label: "Partner Family :", value: "", disabled: true },
  { label: "Father In Law", value: "Father In Law" },
  { label: "Mother In Law", value: "Mother In Law" },
  { label: "Sister In Law", value: "Sister In Law" },
  { label: "Brother In Law", value: "Brother In Law" },
  { label: "Niece In Law", value: "Niece In Law" },
  { label: "Nephew In Law", value: "Nephew In Law" },
  { label: "Uncle In Law", value: "Uncle In Law" },
  { label: "Aunt In Law", value: "Aunt In Law" },
  { label: "Cousin In Law", value: "Cousin In Law" },
  { label: "Grandfather In Law", value: "Grandfather In Law" },
  { label: "Grandmother In Law", value: "Grandmother In Law" },
];

export const alliesOptions = [
  { label: "Social Allies :", value: "", disabled: true },
  { label: "Companion", value: "Companion" },
  { label: "Acquaintance", value: "Acquaintance" },
  { label: "Mentor", value: "Mentor" },
  { label: "Student", value: "Student" },
  { label: "Rival (turned ally)", value: "Rival (turned ally)" },
  { label: "Neighbour", value: "Neighbour" },

  { label: "Professional Allies :", value: "", disabled: true },
  { label: "Colleague", value: "Colleague" },
  { label: "Business Partner", value: "Business Partner" },
  { label: "Employer", value: "Employer" },
  { label: "Employee", value: "Employee" },
  { label: "Client", value: "Client" },
  { label: "Patron", value: "Patron" },
  { label: "Benefactor", value: "Benefactor" },
  { label: "Sponsor", value: "Sponsor" },
  { label: "Apprentice", value: "Apprentice" },
  { label: "Master", value: "Master" },
  { label: "Guild Member", value: "Guild Member" },
  { label: "Guild Leader", value: "Guild Leader" },

  { label: "Military & Adventuring Allies :", value: "", disabled: true },
  { label: "Comrade-in-arms", value: "Comrade-in-arms" },
  { label: "Commander", value: "Commander" },
  { label: "Soldier Ally", value: "Soldier Ally" },
  { label: "Mercenary Partner", value: "Mercenary Partner" },
  { label: "Squad mate", value: "Squad mate" },
  { label: "Battle Brother / Sister", value: "Battle Brother / Sister" },
  { label: "Adventuring Party Member", value: "Adventuring Party Member" },
  { label: "Squire", value: "Squire" },
  { label: "Scout", value: "Scout" },

  { label: "Political & Ideological Allies :", value: "", disabled: true },
  { label: "Faction Member", value: "Faction Member" },
  { label: "Rebel Ally", value: "Rebel Ally" },
  { label: "Diplomatic Contact", value: "Diplomatic Contact" },
  { label: "Spy Contact", value: "Spy Contact" },
  { label: "Political Patron", value: "Political Patron" },
  { label: "Noble Supporter", value: "Noble Supporter" },
  { label: "Revolutionary Ally", value: "Revolutionary Ally" },
  { label: "Cultist Ally", value: "Cultist Ally" },
  { label: "Religious Devotee", value: "Religious Devotee" },
  { label: "Fellow Believer", value: "Fellow Believer" },

  { label: "Supernatural & Otherworldly Allies :", value: "", disabled: true },
  { label: "Familiar", value: "Familiar" },
  { label: "Summoned Creature", value: "Summoned Creature" },
  { label: "Bound Spirit", value: "Bound Spirit" },
  { label: "Guardian Angel", value: "Guardian Angel" },
  { label: "Elemental Ally", value: "Elemental Ally" },
  { label: "Patron", value: "Patron" },
  { label: "Sentient Weapon / Relic", value: "Sentient Weapon / Relic" },
  { label: "Magical Construct", value: "Magical Construct" },
  { label: "Beast Companion", value: "Beast Companion" },

  { label: "Community Allies :", value: "", disabled: true },
  { label: "Local Elder", value: "Local Elder" },
  { label: "Village Leader", value: "Village Leader" },
  { label: "Healer / Doctor", value: "Healer / Doctor" },
  { label: "Teacher", value: "Teacher" },
  { label: "Scholar Ally", value: "Scholar Ally" },
  { label: "Craftsman Ally", value: "Craftsman Ally" },
  { label: "Merchant Ally", value: "Merchant Ally" },
];

export const friendsOptions = [
  { label: "By Bond :", value: "", disabled: true },
  { label: "Best Friend", value: "Best Friend" },
  { label: "Close Friend", value: "Close Friend" },
  { label: "Casual Friend", value: "Casual Friend" },
  { label: "Childhood Friend", value: "Childhood Friend" },
  { label: "Family Friend", value: "Family Friend" },

  { label: "By Role :", value: "", disabled: true },
  { label: "Confidant", value: "Confidant" },
  { label: "Partner-in-Crime", value: "Partner-in-Crime" },
  {
    label: "Drinking Buddy / Leisure Friend",
    value: "Drinking Buddy / Leisure Friend",
  },
  { label: "Work Friend", value: "Work Friend" },
  { label: "Travel Companion", value: "Travel Companion" },
  { label: "Study Friend / Classmate", value: "Study Friend / Classmate" },
  { label: "Sparring Partner", value: "Sparring Partner" },

  { label: "By Nature of Relationship :", value: "", disabled: true },
  { label: "Loyal Friend", value: "Loyal Friend" },
  { label: "Fair-Weather Friend", value: "Fair-Weather Friend" },
  { label: "Long-Distance Friend", value: "Long-Distance Friend" },
  { label: "Rival-Friend", value: "Rival-Friend" },
  { label: "Secret Friend", value: "Secret Friend" },

  { label: "By Depth of Impact :", value: "", disabled: true },
  { label: "Mentor-Friend", value: "Mentor-Friend" },
  { label: "Idolized Friend", value: "Idolized Friend" },
  { label: "Protective Friend", value: "Protective Friend" },
  { label: "Dependent Friend", value: "Dependent Friend" },
  { label: "Unexpected Friend", value: "Unexpected Friend" },
];

export const enemiesOptions = [
  { label: "Personal Enemies :", value: "", disabled: true },
  { label: "Nemesis", value: "Nemesis" },
  { label: "Rival", value: "Rival" },
  { label: "Betrayer", value: "Betrayer" },
  { label: "Backstabber", value: "Backstabber" },
  { label: "Oppressor", value: "Oppressor" },

  { label: "Political & Ideological Enemies :", value: "", disabled: true },
  { label: "Corrupt Official", value: "Corrupt Official" },
  { label: "Rebel Opponent", value: "Rebel Opponent" },
  { label: "Religious Zealot Enemy", value: "Religious Zealot Enemy" },
  { label: "Cultist Enemy", value: "Cultist Enemy" },
  { label: "Rival Faction Member", value: "Rival Faction Member" },

  { label: "Supernatural Enemies :", value: "", disabled: true },
  { label: "Monster Enemy", value: "Monster Enemy" },
  { label: "Undead Enemy", value: "Undead Enemy" },
  { label: "Demon Enemy", value: "Demon Enemy" },
  { label: "Cursed Entity", value: "Cursed Entity" },
  { label: "Dark Sorcerer", value: "Dark Sorcerer" },

  { label: "Other Enemies :", value: "", disabled: true },
  { label: "Bandit Leader", value: "Bandit Leader" },
  { label: "Assassin", value: "Assassin" },
  { label: "Traitor", value: "Traitor" },
  { label: "War Criminal", value: "War Criminal" },
];

export const subordinatesOptions = [
  { label: "Military Subordinates :", value: "", disabled: true },
  { label: "Soldier", value: "Soldier" },
  { label: "Sergeant", value: "Sergeant" },
  { label: "Lieutenant", value: "Lieutenant" },
  { label: "Captain", value: "Captain" },

  { label: "Professional Subordinates :", value: "", disabled: true },
  { label: "Assistant", value: "Assistant" },
  { label: "Secretary", value: "Secretary" },
  { label: "Intern", value: "Intern" },
  { label: "Apprentice", value: "Apprentice" },

  { label: "Other Subordinates :", value: "", disabled: true },
  { label: "Minion", value: "Minion" },
  { label: "Servant", value: "Servant" },
  { label: "Slave", value: "Slave" },
  { label: "Follower", value: "Follower" },
];

export const affiliationsOptions = [
  { label: "Political Affiliations :", value: "", disabled: true },
  { label: "Faction", value: "Faction" },
  { label: "Guild", value: "Guild" },
  { label: "Party", value: "Party" },
  { label: "Clan", value: "Clan" },
  { label: "Tribe", value: "Tribe" },

  { label: "Religious Affiliations :", value: "", disabled: true },
  { label: "Church", value: "Church" },
  { label: "Cult", value: "Cult" },
  { label: "Sect", value: "Sect" },
  { label: "Temple", value: "Temple" },

  { label: "Professional Affiliations :", value: "", disabled: true },
  { label: "Company", value: "Company" },
  { label: "Organization", value: "Organization" },
  { label: "Academy", value: "Academy" },
  { label: "School", value: "School" },
  { label: "Union", value: "Union" },

  { label: "Community Affiliations :", value: "", disabled: true },
  { label: "Village", value: "Village" },
  { label: "City", value: "City" },
  { label: "Nation", value: "Nation" },
];

export const attributesOptions = [
  { key: "strength", label: "Strength", skills: ["Athletics"] },
  {
    key: "dexterity",
    label: "Dexterity",
    skills: ["Acrobatics", "Sleight of Hand", "Stealth"],
  },
  { key: "constitution", label: "Constitution", skills: [] },
  {
    key: "intelligence",
    label: "Intelligence",
    skills: ["Arcana", "History", "Investigation", "Nature", "Religion"],
  },
  {
    key: "wisdom",
    label: "Wisdom",
    skills: [
      "Animal Handling",
      "Insight",
      "Medicine",
      "Perception",
      "Survival",
    ],
  },
  {
    key: "charisma",
    label: "Charisma",
    skills: ["Deception", "Intimidation", "Performance", "Persuasion"],
  },
];

export const combatValueOptions = [
  { value: 0, label: "Commoner", baseValues: [10, 10, 10, 10, 10, 10] },
  { value: 1, label: "Novice", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 2, label: "Adept", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 3, label: "Journeyman", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 4, label: "Veteran", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 5, label: "Champion", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 6, label: "Hero", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 7, label: "Guardian", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 8, label: "Warden", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 9, label: "Paragon", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 10, label: "Legend", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 11, label: "Exemplar", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 12, label: "Vanguard", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 13, label: "Conqueror", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 14, label: "Archon", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 15, label: "Mythic", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 16, label: "Luminary", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 17, label: "Chosen", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 18, label: "Sovereign", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 19, label: "Icon", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 20, label: "World-Hero", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 21, label: "Ascendant", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 22, label: "Oracle", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 23, label: "Transcendent", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 24, label: "Eternal", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 25, label: "Worldbreaker", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 26, label: "High Exemplar", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 27, label: "Titanborn", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 28, label: "Arch-Eternal", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 29, label: "Herald", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 30, label: "Demi-Legend", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 31, label: "Immortal", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 32, label: "Radiant One", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 33, label: "Celestial", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 34, label: "Avatar", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 35, label: "Demi-Deity", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 36, label: "Eternal Flame", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 37, label: "World-Bearer", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 38, label: "God-Touched", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 39, label: "Divine Incarnate", baseValues: [15, 14, 13, 12, 10, 8] },
  { value: 40, label: "Demi-God", baseValues: [15, 14, 13, 12, 10, 8] },
];
